### ISSUE TITLE
Ligatures

### ISSUE THREAD

**Issue by diegolamanno** [pcaro90/hermit#10]
Have you ever consider implement something like [Fira Code with Ligatures](https://github.com/tonsky/FiraCode). I really like Hermit but I cannot lie those ligatures are really good. 

Thanks,

**Comment by pcaro90** [comment]
I don't like ligatures in a monospaced font, I prefer characters to look always the same, without depending on the surrounding glyphs. So I won't implement ligatures in Hermit.

Sorry!
