### ISSUE TITLE
Asymmetry between slash and backslash

### ISSUE THREAD

**Issue by integral-dw** [pcaro90/hermit#15]
Hi,

very lovely font, but there is one thing I don't quite understand: Why did you distinguish the two slashes in such a way that only one rests on the baseline?   I am just genuinely curious why.  I mean, slashes and backslashes are almost always entirely different beasts semantically, so breaking the symmetry makes sense, but I would have expected a play with, say the weight of the characters (maybe the backslash being a bit lighter as it usually serves as an escape character), but not their relative horizontal orientation.

**Comment by pcaro90** [comment]
They are completely symmetrical:

![slash_test](https://user-images.githubusercontent.com/1571486/90380241-191b2f80-e07c-11ea-852c-c1c56cfbf73c.png)

Which variant (light, bold...) are you using?

**Comment by integral-dw** [comment]
All three weights seem to behave like this, for example medium:
![spikes](https://user-images.githubusercontent.com/60486867/90392293-e595d080-e08e-11ea-83e3-edb50e1f3302.png)
I'm on Fedora, and the behavior persists across applications, under both KDE and Cinnamon.

**Comment by pcaro90** [comment]
Are you using v2.0? I slightly tweaked a lot of glyphs in this version, maybe I found the asymmetry and fixed it without documenting the change...

**Comment by integral-dw** [comment]
You're right, the Fedora package `pcaro-hermit-fonts-1.21-13` is not quite up-to-date.
v2.0 has it fixed.
![spikes-v2](https://user-images.githubusercontent.com/60486867/90398423-ade05600-e099-11ea-8083-f6d4aadca83b.png)

**Comment by pcaro90** [comment]
Awesome! :D
