### ISSUE TITLE
download link is missing

### ISSUE THREAD

**Issue by 532910** [pcaro90/hermit#16]
https://pcaro.es/p/hermit/#downloads says:

`You can find a pack with other formats (UFO, WOFF, WOFF2) right here:`

but there are no link afterwords.

**Comment by pcaro90** [comment]
Well...

![image](https://user-images.githubusercontent.com/1571486/92238222-047eca00-eeb9-11ea-917f-4da992244e3e.png)

**Comment by 532910** [comment]
so this is a design issue: both `Download right now and` and `Download full package` looks like a headings.

**Comment by 532910** [comment]
BTW, it's extremely hard to press github button on the top in mobile mode.

**Comment by pcaro90** [comment]
Noted, thank you! :+1:
