### ISSUE TITLE
Cyrillic is too bold

### ISSUE THREAD

**Issue by 532910** [pcaro90/hermit#17]
![image](https://user-images.githubusercontent.com/14617699/92289554-8b638f00-ef19-11ea-836e-d0d624698e8b.png)
![image](https://user-images.githubusercontent.com/14617699/92289556-8d2d5280-ef19-11ea-93cd-90e7187a173d.png)
![image](https://user-images.githubusercontent.com/14617699/92289560-8ef71600-ef19-11ea-886d-092433b98e1f.png)

**Comment by 532910** [comment]
comparison fantasque that looks pretty well
![image](https://user-images.githubusercontent.com/14617699/92290240-16de1f80-ef1c-11ea-9a8f-aeb4d533311d.png)

**Comment by pcaro90** [comment]
Hermit does not contain cyrillic glyphs.

**Comment by 532910** [comment]
It's a pity! ):
