### ISSUE TITLE
Add Bitcoin symbol?

### ISSUE THREAD

**Issue by JasonLeeH** [pcaro90/hermit#3]
http://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf

Unicode just approved U+20BF (₿) and now it needs a home in fonts. Hermit is my favorite font of all time and I use it in all my work. If there was a Hermit-themed Bitcoin symbol, I'd be very grateful. I could even pay you. We could discuss it.

**Comment by pcaro90** [comment]
Sadly, I currently lack the time to review Hermit at all. However, I think it's a good idea, I'll add it to the "To Do" list. Also, it seems a simple task to do, and it shouldn't take a lot of time. Thanks for your suggestion!

**Comment by ysangkok** [comment]
@JasonLeeH approved? Are you sure about that? I think this is just a suggestion.

**Comment by pcaro90** [comment]
Done on Hermit v2.0.

**Comment by JasonLeeH** [comment]
![screen shot 2019-01-19 at 12 15 21 pm](https://user-images.githubusercontent.com/6761181/51430097-ee3cd100-1be3-11e9-9c56-599214c05a8b.png)


Would it be possible to get a BTC glyph which retains line-height? While the other currency symbols are constrained, the BTC symbol drops below the line.
