### ISSUE TITLE
white space's width seems bigger than other character?

### ISSUE THREAD

**Issue by devforma** [pcaro90/hermit#4]
![image](https://cloud.githubusercontent.com/assets/3469890/16641356/59c03e8a-4432-11e6-81d0-618822575b7c.png)

**Comment by pcaro90** [comment]
Sorry, not for me... Maybe a configuration issue?

![seleccion_001](https://cloud.githubusercontent.com/assets/1571486/22896618/20bf7bc6-f221-11e6-9ea7-63643a4e9caf.png)

**Comment by drgomesp** [comment]
Same for me:

![screenshot 2017-05-21 13 41 24](https://cloud.githubusercontent.com/assets/696982/26282874/3c084cea-3e2b-11e7-8134-370790e204b7.png)

There seems to be a slight problem on the width calculation.

**Comment by pcaro90** [comment]
@drgomesp In your case, I think you're using Light version, which does not align properly. That's a known problem, it happens with non-regular sizes (Light and Bold).

**Comment by drgomesp** [comment]
You're right. Medium works well.

**Comment by sigod** [comment]
![image](https://user-images.githubusercontent.com/1175750/45198413-1815dc80-b26f-11e8-80d6-e5c530fa96aa.png)

This issue appears only in DirectWrite if font face is specified only as "Hermit".

**Comment by pcaro90** [comment]
This shouldn't be an issue anymore on Hermit v2.0, even with light and bold weights.
